### ISSUE TITLE
Another unicode problem?

### ISSUE THREAD

**Issue by joto** [mstock/RoomAssets-App-Sync#8]
The generated file name for files contains annoying % escapes. Example:

`Hörsaal_3_K0506_Audimax_2/20-Mittwoch/20-Mittwoch_1740_-_Ein_WebGIS_zur_Öffentlichkeitsbeteiligung_in_Planungsverfahren_des_Netzausbaus_-_GDEAYP-970610/fossgis_2024_St%C3%BCckemann_Ein_WebGIS_zur_%C3%96ffentli_YwGjXgC.pdf`

This is different from the problem before with the room names. They work fine now.

**Comment by mstock** [comment]
This should work better now with the latest changes, I'm using the unescaped path part now instead of manually splitting off the file name from the end of the URL.

**Comment by joto** [comment]
Looks good. Thanks!
